// Claves existentes del formulario; las claves administrativas no las decide la IA.
export const ETIQUETAS_EXTRACCION = {
  "apellidos": "Apellidos",
  "nombres": "Nombres",
  "cedula": "Cédula / pasaporte",
  "sexo": "Sexo",
  "fechaNacimiento": "Fecha de nacimiento",
  "pais": "País",
  "provincia": "Provincia",
  "canton": "Cantón",
  "parroquia": "Parroquia",
  "ciudad": "Ciudad",
  "nacionalidad": "Nacionalidad",
  "calle": "Calle principal",
  "num": "Número de domicilio",
  "transversal": "Calle transversal",
  "telefono": "Teléfono",
  "correo": "Correo alternativo",
  "correoestudiante": "Correo del estudiante",
  "nivelEstudio": "Nivel de estudio",
  "tipoBachiller": "Tipo de título",
  "cursoanterior": "Curso anterior",
  "unidadeducativa": "Unidad educativa",
  "centroformacionanterior": "Centro de formación anterior",
  "conferidoPorA1": "Establecimiento A.1",
  "conferidoPorA2": "Establecimiento A.2",
  "nombrepapa": "Nombre del padre",
  "profesionpapa": "Profesión del padre",
  "ocupacionpapa": "Ocupación del padre",
  "nombremama": "Nombre de la madre",
  "profesionmama": "Profesión de la madre",
  "ocupacionmama": "Ocupación de la madre",
  "nombrerepresentante": "Nombre del representante",
  "ocupacionrepresentante": "Ocupación del representante",
  "domiciliorepresentante": "Domicilio del representante",
  "telefonorepresentante": "Teléfono del representante",
  "lugarfechamatricula": "Lugar y fecha de matrícula",
  "especialidad": "Especialidad",
  "lugarfechacertificado": "Lugar y fecha del certificado"
} as const;
export type CampoExtraido = keyof typeof ETIQUETAS_EXTRACCION;
export type DatosExtraidosMatricula = Partial<Record<CampoExtraido, string>>;
export interface ResultadoLlenado {
  datos: DatosExtraidosMatricula;
  reemplazar: boolean;
}

export const DATOS_MATRICULA_INICIALES = {
  matriculaNo: "",
  tomo: "",
  pagina: "",
  cursoId: '' as string | number,
  apellidos: "",
  nombres: "",
  cedula: "",
  sexo: "",
  fechaNacimiento: "",
  pais: "ECUADOR",
  provincia: "",
  canton: "",
  parroquia: "",
  ciudad: "",
  nacionalidad: "ECUATORIANA",
  calle: "",
  num: "",
  transversal: "",
  telefono: "",
  correo: "",
  correoestudiante: "",
  nivelEstudio: "",
  tipoBachiller: "",
  cursoanterior: "",
  unidadeducativa: "",
  centroformacionanterior: "",
  conferidoPorA1: "",
  conferidoPorA2: "",
  nombrepapa: "",
  profesionpapa: "",
  ocupacionpapa: "",
  nombremama: "",
  profesionmama: "",
  ocupacionmama: "",
  nombrerepresentante: "",
  ocupacionrepresentante: "",
  domiciliorepresentante: "",
  telefonorepresentante: "",
  lugarfechamatricula: "",
  especialidad: "",
  lugarfechacertificado: "",
};
